banner: image/Heart_of_Community.png

headerNav:
  - title: 资讯
    sub:
      - title: 活动
        href: /categories/Activity/
      - title: 博客
        href: /blog
  - title: 下载中心
    href: /download
  - title: 成员
    href: http://member.kaiyuanshe.cn/
  - title: 赞助伙伴
    href: /surport_member
  - title: 资源
    sub:
      - title: 许可证选择器
        href: http://www.kaiyuanshe.cn/license-tool.html
      - title: 开源之星
        href: http://ossstar.kaiyuanshe.cn/
      - title: 开源文档
        href: /categories/Document
  - title: 关于
    sub:
      - title: 介绍
        href: /profile/about
      - title: 工作组
        href: /governance
      - title: 章程
        href: /profile/charter
      - title: 会议纪要
        href: /categories/Meeting

footNav:
  - title: 活动
    href: /categories/Activity/
  - title: 博客
    href: /blog
  - title: 章程
    href: /profile/charter
  - title: 许可
    href: https://github.com/kaiyuanshe/kaiyuanshe/tree/hexo/License
  - title: 语言
    href: https://electronjs.org/languages
  - title: 联系我们
    href: /profile/contact

social:
  github:
    name: kaiyuanshe
    domain: https://github.com
    title: Github Organization
  twitter:
    name: contactkaiyuan1
    domain: https://twitter.com
    title: "@contactkaiyuan1 on Twitter"
  facebook:
    name: kaiyuanshe.china
    domain: https://www.facebook.com
    title: Facebook account

principle:
  - title: 贡献
    icon: feather-alt
  - title: 共识
    icon: handshake
  - title: 共治
    icon: users

mission:
  - title: 开源治理
    icon: code-branch
  - title: 国际桥梁
    icon: link
  - title: 社区发展
    icon: seedling
  - title: 开源项目
    icon: project-diagram

language:
  en-US:
    local: English
  ja-JP:
    local: 日本語
    english: Japanese
  es-ES:
    local: Español
    english: Spanish
  zh-CN:
    local: 中文
    english: Chinese Simplified
    default: true
  tr-TR:
    local: Türkçe
    english: Turkish
  id-ID:
    local: Indonesian
  fil-PH:
    local: Filipino
  fr-FR:
    local: Français
    english: French
  ru-RU:
    local: Русский
    english: Russian
  ko-KR:
    local: 한국어
    english: Korean
  it-IT:
    local: Italiano
    english: Italian
  pt-BR:
    local: Português
    english: Portuguese
  de-DE:
    local: Deutsch
    english: German
  uk-UA:
    local: Українська
    english: Ukrainian
  zh-TW:
    local: 中文
    english: Chinese Traditional
  pl-PL:
    local: język polski
    english: Polish
  bg-BG:
    local: български език
    english: Bulgarian
  hi-IN:
    local: हिन्दी
    english: Hindi
  nl-NL:
    local: Nederlands
    english: Dutch
  vi-VN:
    local: Tiếng Việt
    english: Vietnamese
  ar-SA:
    local: اللغة العربية
    english: Arabic
  fa-IR:
    local: فارسی
    english: Persian
  cs-CZ:
    local: čeština
    english: Czech
  th-TH:
    local: ไทย
    english: Thai
  he-IL:
    local: עברית
    english: Hebrew
  ro-RO:
    local: limba română
    english: Romanian
  tl-PH:
    local: Wikang Tagalog
    english: Tagalog
